version: "3.8"

services:
  web:
    container_name: storefront
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - app:/usr/src/app/
    ports:
      - 7003:8000
volumes:
  app:
